# Generated by Django 2.2.2 on 2019-06-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('-date', 'restaurant', 'id'),
                'default_related_name': 'meals',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('acronym',),
                'default_related_name': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('slack_id', models.CharField(max_length=20)),
                ('favorite_restaurants', models.ManyToManyField(to='lunchinator.Restaurant')),
            ],
            options={
                'verbose_name_plural': 'Users (with favorite restaurants)',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='lunchinator.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='lunchinator.User')),
            ],
            options={
                'default_related_name': 'selections',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='lunchinator.Restaurant'),
        ),
    ]
