# Generated by Django 2.2.2 on 2019-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchinator', '0003_auto_20190620_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('meal', 'user')},
        ),
    ]
