# Generated by Django 2.2.3 on 2019-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchinator', '0004_auto_20190620_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
